// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

declare global {
  interface Window {
    __SUPABASE_CONFIG__?: { url: string; publishableKey: string };
  }
}

function createSupabaseClient() {
  // Reihenfolge, robust gegen Lovables Build-Zeit-vs-Laufzeit-Problem:
  // 1) Vom Server zur Laufzeit injizierte Werte (siehe __root.tsx) -- korrekt
  //    auch wenn Secrets beim Build nicht verfuegbar waren.
  // 2) process.env direkt (SSR-Kontext, laeuft server-seitig).
  // 3) import.meta.env als letzter Fallback (rein clientseitiger Build/Preview
  //    ohne SSR, z. B. lokales `vite build`).
  const injected = typeof window !== "undefined" ? window.__SUPABASE_CONFIG__ : undefined;
  const SUPABASE_URL =
    injected?.url ||
    (typeof process !== "undefined" ? process.env["APP_SUPABASE_URL"] : undefined) ||
    (typeof process !== "undefined" ? process.env["SUPABASE_URL"] : undefined) ||
    import.meta.env["APP_SUPABASE_URL"] ||
    import.meta.env["VITE_SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    injected?.publishableKey ||
    (typeof process !== "undefined" ? process.env["APP_SUPABASE_PUBLISHABLE_KEY"] : undefined) ||
    (typeof process !== "undefined" ? process.env["SUPABASE_PUBLISHABLE_KEY"] : undefined) ||
    import.meta.env["APP_SUPABASE_PUBLISHABLE_KEY"] ||
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["APP_SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["APP_SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
